# Computer is Friend

The theme of this lesson is understanding the difference between hardware and 
software, and where things are stored on your computer. In part two of the 
coursework, you will learn good practices for managing and storing files for 
this course. 

Before you learn how to program, it can be helpful to learn a few simple things
about how computers work. Modern computers hide a lot of the about where and how
files are stored, but later in the course when you start writing programs these
details will suddenly become very important.


::: callout
## Learning Objectives

+ Explain the difference between hardware and software
+ Define operating system terminology: hard drive, memory, file system, directory, system paths
+ Describe how these concepts work together to keep your computer running
+ Explain where files live on your laptop
+ Create a class folder in your Documents
+ Install R & RStudio
+ Recognize how R differs from RStudio
:::

<!-- Not sure if we want this type of preview summary -->

<!-- #### 📖 Readings: 45 minutes -->

<!-- #### 📽 Watch Videos: 30 min -->

<!-- #### 💻 Activities: 5-10 min -->

<!-- #### ✅ Check-ins: 2 -->

# Hardware {#hardware}

The components that make up the physical computer are the **hardware**. This
3-minute video is focused on desktops, but the same components are commonly
found in laptops, cell phones, and even smart watches.

{{< video https://www.youtube.com/embed/Rdm8E59L8Og >}}

::: {.callout-tip}
# Learn About Your Computer

Examine the hardware on your computer using one of the following methods:

Windows: Ctrl+Shift+Escape > Task Manager > More Options > Performance tab

Mac: Apple menu > System Settings > General (sidebar) > About > System Report

<!-- Linux: The inxi command will give you most of this on the command line, and hwinfo --short will give you a considerably more detailed printout. -->

Find out:

- What processor do you have?
This most likely will start with ARM, Intel, AMD, or Apple M*

- How much RAM do you have? (most likely between 8 and 64 GB)

- How much hard drive space do you have?
:::

## Operating Systems {#operating-systems}

Operating systems (OS), such as Windows and MacOS, are sophisticated programs that
allow CPUs to keep track of multiple programs and tasks and execute them at the
same time. This 2-minute video describes different operating systems. 

::: youtube-video-container
{{< video https://www.youtube.com/embed/RhHMgkUdhdk >}}
:::

Broadly, you should know (1) what operating system your computer uses
(Windows / Mac / Linux), and (2) what version of the system your computer uses
(e.g. Windows 11, Mac OSX Tahoe, Debian 12, RedHat 7).

::: {.callout-tip}
# Learn About Your Computer

Locate your operating system and version information.
When was your system last updated?

If your system hasn't been updated in a while, consider updating it now. System
updates may break software you'll install to work with R in the next few weeks. 
:::

## File Systems {#file-systems}

File systems are places you save files (shocking!). These systems are modeled
after physical file cabinets, where documents are kept in a hierarchical 
sequence of folders. This collection of folders is what is stored on your 
hard drive. 

There has been a generational shift in how computers are used. Older users
(like me!) were taught to organize files deliberately, while many newer users
rely almost entirely on search, treating their computers less like filing
cabinets and more like laundry hampers.

Regardless of how you tend to organize your personal files, it is helpful to
understand the basics of what is meant by a computer **file system**--a way to
organize data stored on a hard drive. 

::: youtube-video-container
{{< video https://www.youtube.com/embed/BV0-EPUYuQc >}}
:::

::: {.callout-note}
# You can stop watching at 4:16.
:::

### File Paths {#file-paths}

It's not enough to know about a computer's file system, we also need to know how
computers remember the location of what is stored where. Specifically, we need
to understand **file paths**.

::: youtube-video-container
{{< video https://www.youtube.com/embed/BMT3JUWmqYY >}}
:::

<!-- When you write a program, you may have to reference external files - data stored in a .csv file, for instance, or a picture. Best practice is to create a file structure that contains everything you need to run your entire project in a single file folder (you can, and sometimes should, have sub-folders). -->

<!-- For now, it is enough to know how to find files using file paths, and how to refer to a file using a relative file path from your base folder. In this situation, your "base folder" is known as your **working directory** - the place your program thinks of as home. -->

<!-- In Chapter 1, we will discuss [Directories, Paths, and Projects](#directories-and-projects) as they relate to `R` and getting setup to be successful in this course. -->

<!-- ### File Names -->

<!-- Stuff on good file naming practices -->


<!-- ## Software -->

<!-- Installing R and RStudio -->