project:
  type: book
  output-dir: docs

book:
  title: "R is Your Friend"
  author: "Cal Poly - SLO, Statistics Department"
  date: last-modified
  chapters:
  - index.qmd
  - part: "**Fundamentals of Coding**"
    chapters: 
    - text: "Chapter 0: Setup"
      href: 00-setup.qmd
    - text: "Chapter 1: What is code?"
      href: 01-what-is-code.qmd
    - text: "Chapter 2: R is Friend"
      href: 02-r-is-friend.qmd
    - text: "Chapter 3a: Control Flow"
      href: 03a-control-flow.qmd
    - text: "Chapter 3b: Writing Simple Functions"
      href: 03b-writing-functions.qmd
    - text: "Chapter 4: Data is Friend"
      href: 04-data-is-friend.qmd
  - part: "**Data Wrangling and Visualization**"
    chapters:
    - text: "Chapter 5: Data Visualizations"
      href: 05-data-visualizations.qmd
    - text: "Chapter 6: Data Wrangling"
      href: 06-data-wrangling.qmd
    - text: "Chapter 7: More Wrangling"
      href: 07-more-wrangling.qmd
    - text: "Chapter 8a: Data Joins"
      href: 08a-joins.qmd
    - text: "Chapter 8b: Factors"
      href: 08b-factors.qmd
    - text: "Chapter 9a: Strings"
      href: 09a-strings.qmd
    - text: "Chapter 9b: Dates"
      href: 09b-dates.qmd
    - text: "Chapter 10: Communication"
      href: 10-communication.qmd
  - part: "**Modeling and Functions**"
    chapters:
    - text: "Chapter 12: Writing More Complex Functions"
      href: 12-more-functions.qmd
    - text: "Chapter 13: Regression"
      href: 13-regression.qmd
    - text: "Chapter 14: Simulation"
      href: 14-simulation.qmd
  site-url: https://r-is-your-friend.github.io/course-pack/
  repo-url: https://github.com/R-is-your-friend
  repo-branch: main
  sharing: [twitter, facebook, linkedin]

# bibliography: references.bib

from: markdown+emoji

format:
  html:
    # theme: cosmo
    code-link: true
    theme:
      light: [flatly, customcallouts.scss]
      dark: [darkly, customcallouts.scss]
    code-copy: true
    code-annotations: below
    toc-depth: 4
  # pdf:
  #   documentclass: scrreprt

filters:
  - custom_callout.lua
    
execute: 
  echo: true
  warning: false
  error: true
  freeze: auto
