{
  "hash": "187efe0632a24f6999938bd0b12d371f",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n - flourish\n---\n\n\n\n\n\n# Control Flow\n\n::: callout\n## Learning Objectives\n\n- What a conditional statement is\n- How to create a simple conditional statement with `if ()` and `else`\n- How to series of conditional statements with `else if ()`\n- What it means for a function to be vectorized\n- How to make a vectorized conditional statement\n- Where to access help on an R function\n- Recognize when to use a `for ()` loop instead of a `while ()` loop\n- Understand how to index a loop\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nControl flow refers to statements in a computer program that that determines \nwhen, how, and how many times code is evaluated. In this reading you will learn\nabout the two main types of control flow structures---`if` statements and\n`for()` loops.\n\n## Conditionals in Everyday Life\n\nWe are going to teach you about conditionals in R, but before we do it is good\nto remember that we use these types of statements *all* the time. Anytime you\nuse if-then logic you are using a conditional!\n\n![Image from Randal Munroe, xkcd.com, available under a CC-By 2.5 license.](images/03-conditionals.png){fig-alt=\"A comic of a stick person and a series of speech bubbles. The person says 'I'll be in your city tomorrow if you want to hangout.' The person they are talking to (presumably in the background) responds 'But where will you be if I don't want to hang out?' The person then says 'You know, I just remembered I'm busy.' The bottom of the comic says 'Why I try not to be pedantic about conditionals.\"}\n\nThese ideas go back to the practice activity we did with paper airplanes. With\nconditionals, we need to state *exactly* what we mean because the computer will\ndo whatever we tell it to do.\n\n## Conditional Statements\n\nA conditional statement determines what code is evaluated. In general,\nconditional statements look something like this:\n\n```         \nif (condition){\n  stuff to do\n}\n  else{\n  other stuff to do\n}\n```\n\nWhen the computer encounters a conditional statement, it first checks to see if\nthe condition is met (`TRUE`) or if is is not met (`FALSE`). If the condition is\n`TRUE`, then the computer will execute the \"stuff to do\" inside the first set of\n`{}`. If the condition is `FALSE`, then the computer will execute the \"other\nstuff to do\" inside the second set of `{}`\n\n### Conditional Statements in R\n\nIn R, conditional statements look something like this:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 3\n\nif (x > 2) { \n  y <- 8\n  } else {\n  y <- 4\n  }\n```\n:::\n\n\n\n\n\nThere are a few things we need to notice about the syntax. First, we are using\ntwo words `if` and `else` to build the control flow. These are reserved names\nthat R recognizes exactly for this type of task. Second, the condition being\nchecked comes after `if` and is contained in parentheses (`x > 2`). The \"stuff\nto do\" when the condition is `TRUE` is enclosed in `{}` **immediately after**\nthe `if()` statement. If the condition is `FALSE`, then R will execute the \n\"other stuff to do\" contained in the `{}` after `else`.\n\n**What value should `y` have?**\n\n::: callout-important\n# Code Style\n\nWe could have written the above code as:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (x > 2) y <- 8  else y <- 4\n```\n:::\n\n\n\n\n\nand we would have gotten the same result. So, why should we make our code so\n**long**?\n\nA braced expression, `{}`, defines the most important hierarchy of R code. So, \nwe want to make the hierarchy easy to understand. To do this, our code should\nfollow these three principles:\n\n1.  A `{` should be the last character on the line (e.g., `if (x > 2) {` ).\n\n2.  The contents *inside* the `{` should be indented by two spaces.\n\n3.  A `}` should be the first character on the line (e.g., `} else {`)\n\n4.  A space should be included between `if` and the `(` starting the condition\n\nEach of these principles of code style come from the \n[Syntax section of the tidyverse style guide](https://style.tidyverse.org/syntax.html). \nWe will use this style guide throughout the course!\n:::\n\n::: {.callout-check-in}\n1. Which of the following is the correct way to format a conditional statement?\n\n(a)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (num < 100){\n  print(num)\n}\nelse {\n  print(\"banana\")\n}\n```\n:::\n\n\n\n\n\n(b)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (num < 100){\n  print(num)\n} else {\n  print(\"banana\")\n}\n```\n:::\n\n\n\n\n\n(c)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (num < 100){ print(num) } else { print(\"banana\") }\n```\n:::\n\n\n\n\n\n(d)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (num < 100) print(num) else print(\"banana\") \n```\n:::\n\n\n\n\n\n:::\n\n### Conditional Statements as Diagrams\n\nWe find it quite useful to represent conditional statements as diagrams. By\ndrawing out the diagram (even if it is simple), you can more clearly anticipate\nwhat the result of the process will be.\n\n![Diagram of a simple conditional (if/else) statement](images/03-simple-conditional-diagram.png){fig-alt=\"A simple diagram of what comprises an if/else conditional. At the top there is a green diamond and the inside of the diamond reads 'Condition to Check'. There are two arrows exiting the diamond, one pointing to the right that reads 'TRUE' and one pointing down that reads 'FALSE'. These represent the outcome of the conditional check. At the end of the 'TRUE' arrow there is a rectangle that reads 'Thing to do' representing what is done if the condition is met (TRUE). As the end of the 'FALSE' arrow there is a circle that reads 'Other thing to do' representing what is done if the condition is not met (FALSE).\" width=\"60%\"}\n\n::: {.callout-check-in}\n2. With `if` + `else` you have ____ condition(s) to check and ____ possible \noutcome(s).\n:::\n\n## Chaining Conditional Statements\n\nIn our previous conditional statement we only used `if` and `else`, but that\nonly works if you have **two** possible outcomes or **one** condition you need\nto check. In many cases we have more than one condition to check, so we will\nneed to modify our conditional statement.\n\nWhen we have more than one condition to check, we can use an `else if ()`\nstatement. `else if ()` works similar to an `if ()` statement, where you specify\na condition to check in the parentheses. This looks something like:\n\n```         \nif (condition 1) {\n  stuff to do \n} else if (condition 2) {\n  other stuff to do\n} else {\n  other other stuff to do\n}\n```\n\n### Multiple Conditions for Tax Brackets\n\nSuppose we wanted to create conditional statements to know how much in federal\ntaxes someone in the US might pay. Based on the [current IRS tax rates](https://www.irs.gov/filing/federal-income-tax-rates-and-brackets) we have\nthe following outcomes[^03-control-flow-1]:\n\n| Income Range         | Taxes |\n|----------------------|-------|\n| \\$0 to \\$11,925      | 10%   |\n| \\$11,926 to \\$48,475 | 12%   |\n| \\$48,476 \\$103,350   | 22%   |\n| \\$103,351 \\$197,300  | 24%   |\n| \\$197,301 \\$250,525  | 32%   |\n| \\$250,526 \\$626,350  | 35%   |\n| \\$626,351 and above  | 37%   |\n\n[^03-control-flow-1]: Technically, this is a bit of an over simplification. \nIf you make $75,000 you actually pay 10% for the first $11,925, then 12% for the\nnext $36,550 (to get to $48,475), then 22% for the final $26,525. \n\n**Step 1:** Draw out the diagram for the conditional statements. What conditions\nare being checked at each stage? If a condition is true what is the outcome? If \na condition is false, what happens?\n\n::: {.callout-tip collapse=\"true\"}\n# Check Your Answer\n\n![](images/03-taxes-flowchart.png){fig-alt=\"A flowchart for figuring out what tax bracket someone should pay. The chart starts with an orange circle indicating the income (a numeric value) is being input into the flowchart. From there, there are a series of green diamonds each with a check for the income (e.g., income < $11,925). At each diamond there is an arrow pointing down with a value of TRUE next to the arrow, indicating that the condition checked was found to be TRUE. There is a second arrow pointing to the right with a value of FALSE next to the arrow, indicating that the contition checked was found to be false. Beneath each condition that found to be TRUE there is a blue rectangle with a tax percentage indicating the tax rate for that income bracket.\"}\n:::\n\n\n**Step 2:** Translate your diagram into R code!\n\n::: {.callout-tip collapse=\"true\"}\n# Check Your Answer\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (income < 11925) {\n  0.10\n} else if (income <= 48475) {\n  0.12\n} else if (income <= 103350) {\n  0.22\n} else if (income <= 197300) {\n  0.24\n} else if (income <= 250525) {\n  0.32\n} else if (income < 626350){\n  0.35\n} else {\n  0.37\n}\n```\n:::\n\n\n\n\n:::\n\nOkay, let's try it out! A \"typical\" Assistant Professor in the College of \nScience and Math at Cal Poly makes $95,000. Based on your diagram, how much\nwould a professor pay in taxes?\n\nLet's check! Setting `income` to `95000`, our conditional statements tell us\nthat the professor will pay `0.22` or 22% in taxes.\n\n<!-- [WEBR?] -->\n<!-- The code below could just be included in a code chunk so the students can run -->\n<!-- it to prove to themselves that the output will be 0.22. -->\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome <- 95000\n\nif (income < 11925) {\n  0.10\n} else if (income <= 48475) {\n  0.12\n} else if (income <= 103350) {\n  0.22\n} else if (income <= 197300) {\n  0.24\n} else if (income <= 250525) {\n  0.32\n} else if (income < 626350){\n  0.35\n} else {\n  0.37\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.22\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.callout-check-in}\n3. In the IRS tax brackets we had ____ possible outcomes and ____ conditions\nthat needed to be checked. \n\n4. In general, if you have $n$ possible outcomes, you will **always** have\n____ conditions to check. \n:::\n\nWhat if we tried salaries for a variety of CSU employees? Jeffrey Armstrong,\nCal Poly's President is paid $611,203 [^03-control-flow-2], Midred Garcia, \nthe CSU Chancellor is paid $795,000 [^03-control-flow-3], and a full-time\njanitor at Cal Poly can expect to make somewhere around $45,000. \n\n[^03-control-flow-2]: Armstrong is also provided a house on Cal Poly's campus. \n[^03-control-flow-3]: Garcia is also provided $96,000 for housing and $80,000 \nfor deferred compensation.\n\nLet's put these three salaries through our conditional statements to figure out\nhow much each employee will pay in taxes. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome <- c(611203, 795000, 45000)\n\nif (income < 11925) {\n  0.10\n} else if (income <= 48475) {\n  0.12\n} else if (income <= 103350) {\n  0.22\n} else if (income <= 197300) {\n  0.24\n} else if (income <= 250525) {\n  0.32\n} else if (income < 626350){\n  0.35\n} else {\n  0.37\n}\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in if (income < 11925) {: the condition has length > 1\n```\n\n\n:::\n:::\n\n\n\n\n\nOh no! Our conditionals didn't work. What happened? \n\nThe error message we got (`\"the condition has length > 1\"`) may seem strange at\nfirst, but it is actually **incredibly** informative. \n\nWhat the error is telling us is that `if (income < 11925)` could not be\nevaluated because `income` has a length that is greater than 1.\nIf we examine `income < 11925`, we notice that it returns a vector of three \n`TRUE/FALSE` results; one for each of the three incomes.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome < 11925\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE FALSE FALSE\n```\n\n\n:::\n:::\n\n\n\n\n\nTherefore, our code was equivalent to `if(c(FALSE, FALSE, TRUE))`.  An `if()`\nstatement needs a single \"yes/no\" to determine if the code inside gets run or\nnot, so these statements can only work for scalar vectors (i.e., vectors with a\nsingle value)\n\n## Vectorized Operations\n\nSo, what do we do if we want to apply a process using conditional statements \nto *all* the elements in a vector of values? Well, we need to switch from using \n`if ()`, `else if ()`, and `else` to using functions that accept vectors of values. \n\nLuckily for us, vectorized operations are very common in R! Take for example\nfinding the square root of a given number. The `sqrt()` function accepts a \n**vector** of values, applies the square root calculation to *each value*, and\noutputs a vector of the results. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnums <- c(3, 4, 9, 12, 16, 20, 25)\nsqrt(nums)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.732051 2.000000 3.000000 3.464102 4.000000 4.472136 5.000000\n```\n\n\n:::\n:::\n\n\n\n\n\n### Vectorized Conditional Statements\n\nFor our problem, we need to find a similar function that can accept a vector \nof salaries and match each salary with a tax rate. The `case_when()` function\nfrom the **dplyr** package does just that. \n\nThe syntax for this function looks like this:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ncase_when(income < 11925 ~ 0.10, \n          income <= 48475 ~ 0.12, \n          income <= 103350 ~ 0.22, \n          income <= 197300 ~ 0.24, \n          income <= 250525 ~ 0.32, \n          income < 626350 ~ 0.35, \n          .default = 0.37\n          )\n```\n:::\n\n\n\n\n\nLet's break it down! You should first notice that each \"case\" is a separate \nargument to the function. Meaning, each case is separated by a `,`. In our \ncode, there are seven total cases. \n\nWithin a case, there are two components, (1) the left hand side (LHS) and the \nright hand side (RHS). The LHS is the condition that is being checked. This is\nthe same as what went inside of an `if ()` or an `else if ()`. \n\nIn the middle you see a `~` symbol. You can read this as \"then.\" Meaning, if the\ncondition on the LHS is `TRUE` **then** something should happen. What should \nhappen? Well, that is exactly what the RHS specifies. \n\nThe last, somewhat odd looking syntax is the `.default` at the end. This is \nsimilar to the `else {}` at the end of our conditional statements, where both\nare used as a \"catch all\" for cases that were not specified. \n\nBut, does it work? Can `case_when()` provide a vector of tax brackets?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome <- c(611203, 795000, 45000)\n\ncase_when(income < 11925 ~ 0.10, \n          income <= 48475 ~ 0.12, \n          income <= 103350 ~ 0.22, \n          income <= 197300 ~ 0.24, \n          income <= 250525 ~ 0.32, \n          income < 626350 ~ 0.35, \n          .default = 0.37\n          )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.35 0.37 0.12\n```\n\n\n:::\n:::\n\n\n\n\n\nYes!!!\n\n::: {.callout-check-in}\n5. A function is \"vectorized\" if it accepts a \n[vector / matrix / dataframe / list] with length \n[equal to / greater than / less than] 1 as an input. \n\n:::\n\n## Help tab\n\nYou might be wondering, how would I have figured out the syntax for `case_when()`\non my own? Well, let's introduce you to the Help tab---your friend for getting \nhelp with how to use an R function.\n\nThere are two ways to pull up the help file for a function. First, you can type\na `?` before the function's name `?case_when` in your Console. Second, you \ncan type the name of the function in the search bar in the upper right corner\nof the Help tab. \n\nEither option should get you to a page that looks like this:\n\n![](images/03-case-when-help.png){fig-alt=\"A screenshot of the 'Help' tab in RStudio, where you can read documentation pages for R functions. There is a black diamond around the 'Help' title indicating that the purpose of the tab. There is a orange box around the search bar in the upper right corner indicating this is where you can search for a function's name. The help file displayed is for the case_when function in the dplyr package. The upper left corner of the documentation page displays the name of the function, followed by the name of the package the function lives in. Below, a title and description display what the purpose of the function is. Finally, at the bottom, an annotation arrow indicates that the 'arguments, value, and examples' can be found further down the page.\" width=\"70%\"}\n\nThere are three parts to the help file:\n\n1. The function arguments (inputs)\n2. The function value (output)\n3. Examples of how the function can be used\n\nIn the arguments for `case_when()` the documentation says \"A sequence of\ntwo-sided formulas. The left hand side (LHS) determines which values match this\ncase. The right hand side (RHS) provides the replacement value.\" This **is not**\nintuitive for someone who's never used this function. This is why we recommend \nlooking over the examples first!\n\nThe documentation makes a bit more sense looking at the first example. We can\nmore clearly see the LHS (` x %% 35 == 0`), which determines which values match\nthis case. We see the right hand side `\"fizz buzz\"` which provides the\nreplacement value. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:70\n\ncase_when(\n  x %% 35 == 0 ~ \"fizz buzz\",\n  x %% 5 == 0 ~ \"fizz\",\n  x %% 7 == 0 ~ \"buzz\",\n  .default = as.character(x)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"1\"         \"2\"         \"3\"         \"4\"         \"fizz\"      \"6\"        \n [7] \"buzz\"      \"8\"         \"9\"         \"fizz\"      \"11\"        \"12\"       \n[13] \"13\"        \"buzz\"      \"fizz\"      \"16\"        \"17\"        \"18\"       \n[19] \"19\"        \"fizz\"      \"buzz\"      \"22\"        \"23\"        \"24\"       \n[25] \"fizz\"      \"26\"        \"27\"        \"buzz\"      \"29\"        \"fizz\"     \n[31] \"31\"        \"32\"        \"33\"        \"34\"        \"fizz buzz\" \"36\"       \n[37] \"37\"        \"38\"        \"39\"        \"fizz\"      \"41\"        \"buzz\"     \n[43] \"43\"        \"44\"        \"fizz\"      \"46\"        \"47\"        \"48\"       \n[49] \"buzz\"      \"fizz\"      \"51\"        \"52\"        \"53\"        \"54\"       \n[55] \"fizz\"      \"buzz\"      \"57\"        \"58\"        \"59\"        \"fizz\"     \n[61] \"61\"        \"62\"        \"buzz\"      \"64\"        \"fizz\"      \"66\"       \n[67] \"67\"        \"68\"        \"69\"        \"fizz buzz\"\n```\n\n\n:::\n:::\n\n\n\n\n\nThe documentation says the cases are specified as \"two-sided formulas\" which \nsounds confusing. All this means is there is a `~` separating the LHS from the \nRHS, which is apparent in all the examples provided:\n\n<!-- Reading a bit further, we learn that if a `.default` isn't specified then  -->\n<!-- `case_when()` will output an `NA`: -->\n\n<!-- ```{r} -->\n<!-- #| label: case-when-docs-example-2 -->\n\n<!-- # If none of the cases match and no `.default` is supplied, NA is used: -->\n<!-- case_when( -->\n<!--   x %% 35 == 0 ~ \"fizz buzz\", -->\n<!--   x %% 5 == 0 ~ \"fizz\", -->\n<!--   x %% 7 == 0 ~ \"buzz\" -->\n<!-- ) -->\n<!-- ``` -->\n\n::: {.callout-opinion}\nIn our opinion, learning how to read the \"docs\" (documentation pages) for \nfunctions in R is a critical skill. You would think that since these\ndocumentation pages are visible on the Internet, that you could just ask AI to\ngive you this information. But, you'd be surprised the number of things AI can\nget wrong about how a function works. \n\nInstead of wasting your time figuring out whether AI is giving you reasonable\nadvice, why not go straight to the source? Read the R help files!\n:::\n\n::: {.callout-check-in}\n\n6. Which of the following options would open the help file for the `mean()`\nfunction? Select all that apply!\n\n(a) Type `mean` in the Console\n(b) Type `?mean` in the Console\n(c) Search for mean in the search bar of the Packages tab\n(d) Search for mean in the search bar of the Help tab\n:::\n\n### Finding New (Fun) Arguments\n\nThrough this help page, we can learn about new arguments we didn't even know\nabout. Take for example you can set `.unmatched = \"error\"`. This allows you to \nsee if the cases you've provide are actually exhaustive or if there are\nobservations falling outside the possibilities you've defined. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum <- -10:10\n\ncase_when(num < 0 ~ \"negative\", \n          num > 0 ~ \"positive\", \n          .unmatched = \"error\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `case_when()`:\n! Case 3 (`\"error\"`) must be a two-sided formula, not the string\n  \"error\".\n```\n\n\n:::\n:::\n\n\n\n\n\nHere we are getting an error because the 11th entry of `num` (0) does not have\na case it is matched to. We only have positive and negative numbers! So, we\nshould add a third case!\n\n::: columns\n::: {.column width=\"48%\"}\n**Keeping the `.unmatched` argument:**\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncase_when(num < 0 ~ \"negative\", \n          num > 0 ~ \"positive\",\n          num == 0 ~ \"zero\",\n          .unmatched =  \"error\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `case_when()`:\n! Case 4 (`\"error\"`) must be a two-sided formula, not the string\n  \"error\".\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n**Setting the `.default` (removing the `.unmatched` argument):**\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncase_when(num < 0 ~ \"negative\", \n          num > 0 ~ \"positive\",\n          .default = \"zero\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"negative\" \"negative\" \"negative\" \"negative\" \"negative\" \"negative\"\n [7] \"negative\" \"negative\" \"negative\" \"negative\" \"zero\"     \"positive\"\n[13] \"positive\" \"positive\" \"positive\" \"positive\" \"positive\" \"positive\"\n[19] \"positive\" \"positive\" \"positive\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n:::\n\n::: {.callout-check-in}\n7. The `.unmatched` argument of `case_when()` throws an error when ____. \n\n8. The `.default` argument of `case_when()` sets a default value for inputs that\n____. \n\n9. True or false, you can use **both** the `.unmatched` and `.default`\narguments. Meaning you can set `.unmatched =  \"error\"` **and** \n`.default = \"zero\"`?\n\n:::\n\n## Loops\n\nLooping is another form of control flow. Where conditionals largely determine\n*when* and *how* code is evaluated, looping decides **how many times** code is\nrun. With looping, the same set of instructions can be repeated many times. \n\nTake for example the classic problem of updating a variable based on its \ncurrent value. This would be a series of statements like `x <- x + 1`. To \naccomplish this we first need to initialize a value for `x`, so we know where\nto start counting. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 0 \n```\n:::\n\n\n\n\n\nOnce `x` is initialized, we need to know when we should stop adding values. This\nquestion (\"When should the loop stop?\") is what separates between the two types\nof loops---`while()` loops and `for()` loops. \n\n### `while ()` Loops\n\nA `while ()` loop specifies a set of instructions that should be done **while** \na condition is met (`TRUE`). Let's say we want to keep adding values to `x`\nuntil `x` has the value of `10`. So, we want to check the current value of `x`, \nand if the current value is less than 10 then we are okay with the loop\ncontinuing. However, as soon as `x` is greater than or equal to 10 we want the \nloop to end. \n\nWe can write this as a relational comparison: `x < 10`. If the current value of\n`x` is less than 10, this relational statement will return `TRUE`. If the \ncurrent value of `x` is 10, this relational statement will return `FALSE`\nbecause we used a strict inequality. \n\nAs with all coding processes, it is great to start with a diagram of how the \nprocess works **before** translating it into R code!\n\n::: {.panel-tabset}\n\n## Flow Chart\n\n![](images/03-while-loop-flowchart.png){width=\"50%\" fig-alt=\"A flowchart of the steps associated with a while loop. At the top there is an orange circle with an 'x' inside it and an arrow pointing down into the next step. This circle represents the current value of x being fed into the loop. The next step is represented by a green diamond with 'x < 10' written inside it. This is the relational statement being checked at each step of the loop. If the relation is found to be true, there is an arrow pointing to a blue rectangle with 'x <- x + 1' written inside. This indicates that if the value of x is less than 10 then the loop will add 1 to the current value of x. If the relation is found to be false, there is an arrow pointing to the right to a rectangle with 'end loop' written inside. This indicates that once the current value of x is greater than or equal to 10 the loop will stop.\"}\n\n## R Code\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhile (x < 10){\n  x <- x + 1\n}\n```\n:::\n\n\n\n\n:::\n\n\n**What do you think the value of `x` is?**\n\n::: {.callout-tip collapse=\"true\"}\n# Check Your Answer\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n\nA common addition to loops is using the `print()` function to output the current\nvalue of `x`. This seems somewhat benign now, but a `print()` is an incredibly \nhelpful tool in debugging! Adding a `print()` statement to your loop gives you \na snapshot of each iteration, and can tell you where your loop is breaking. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 0\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwhile (x < 10){\n  print(x)\n  x <- x + 1\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n[1] 1\n[1] 2\n[1] 3\n[1] 4\n[1] 5\n[1] 6\n[1] 7\n[1] 8\n[1] 9\n```\n\n\n:::\n:::\n\n\n\n\n\n### `for()` Loops\n\nAnother type of loop is a `for ()` loop. A `for ()` differs from a `while ()` \nloop in that the loop is executed a specific number of times. This is what is \noften referred to as a \"definite\" loop. With a `while ()` loop we do not \nspecify the number of times the loop should be run. Instead, we specify the \ncondition under which the loop should stop (e.g., `x < 10`). This is what is \nreferred to as an \"indefinite\" loop.\n\nThe following graphic provides a fun exploration of a `for ()` loop (in \nconjunction with a conditional statement!):\n\n![A visual demonstration of for loops iterating through a vector of monsters to dress them up for a parade. Image by [Allison Horst](https://allisonhorst.com/allison-horst).](https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/3a446c03-34c7-470e-b147-1ae3d1321503_rw_3840.png?h=9b2c6ebeee7504e4c1a44dffe0707a35){fig-alt=\"Illustrated for loop example. Input vector is a parade of monsters, including monsters that are circles, triangles, and squares. The for loop they enter has an if-else statement: if the monster is a triangle, it gets sunglasses. Otherwise, it gets a hat. The output is the parade of monsters where the same input parade of monsters shows up, now wearing either sunglasses (if triangular) or a hat (if any other shape).\"}\n\nHere, we initialize a set of monsters inside the vector `parade`. The `for ()`\nloop declares that it will iterate (keep repeating) until every element \n`parade` (`monster`) has been used. The body of the loop declares what should \nbe done to each `monster` (put on a hat, put on sunglasses). \n\n#### Indexing a Loop\n\nIn the above graphic `monster` is used as the counter (index) of the `parade` \nvector. This might seem a bit confusing at first because the elements of \n`parade` don't have the name \"monster.\" Rather, the elements of `parade` are \nassociated with an **index** (e.g., `parade[1]`). However, a `for ()` loop \nallows us to index the values we are looping over in a variety of ways. \n\nLet's explore different indexing methods with the `month.name` vector that \ncomes built-in to R:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth.name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"January\"   \"February\"  \"March\"     \"April\"     \"May\"       \"June\"     \n [7] \"July\"      \"August\"    \"September\" \"October\"   \"November\"  \"December\" \n```\n\n\n:::\n:::\n\n\n\n\n\nSuppose we wanted to loop over the values of `month.names` to print out the name\nof every month[^03-control-flow-4]. There are a few different ways we could go\nabout this. \n\nFirst, we could take a similar approach as the graphic about and use a word \n(`month`) to increment the values of `month.name`. Notice that the loop still \nworks if we use the letter `i` to increment. The word you use is not important, \nit is *how* you use it! Namely, the name you use to increment the loop needs to\nbe the **same** name you use *inside* the loop (`print(i)`). \n\n::: columns\n::: {.column width=\"48%\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (month in month.name){\n  print(month)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"January\"\n[1] \"February\"\n[1] \"March\"\n[1] \"April\"\n[1] \"May\"\n[1] \"June\"\n[1] \"July\"\n[1] \"August\"\n[1] \"September\"\n[1] \"October\"\n[1] \"November\"\n[1] \"December\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in month.name){\n  print(i)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"January\"\n[1] \"February\"\n[1] \"March\"\n[1] \"April\"\n[1] \"May\"\n[1] \"June\"\n[1] \"July\"\n[1] \"August\"\n[1] \"September\"\n[1] \"October\"\n[1] \"November\"\n[1] \"December\"\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n:::\n\nAnother option that you might see is specifying the exact number of times the \nloop should be done using numeric values. Take for example this loop:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in 1:12){\n  print(month.name[i])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"January\"\n[1] \"February\"\n[1] \"March\"\n[1] \"April\"\n[1] \"May\"\n[1] \"June\"\n[1] \"July\"\n[1] \"August\"\n[1] \"September\"\n[1] \"October\"\n[1] \"November\"\n[1] \"December\"\n```\n\n\n:::\n:::\n\n\n\n\n\nThis loop specifies that it should be run exactly 12 times (for values `1` \nthrough `12`). For each value of `i`, we print out the associated value of \n`month.names`. For example, when `i = 5`, the loop will print out \n`month.name[5]` which is `May`. \n\nWe can no longer use `print(i)` in our loop because `i` is referring to the\nvalue of the counter (`1:12`) and not the value of `month.name`. Meaning, if we\nhad `print(i)` inside the loop we would end up with the values `1:12` being\noutput. \n\n::: {.callout-important}\n# Fundamentals of Indexing\n\nRegardless of what method you choose, the values used to index a loop **must\ncome from a vector**. Each of these methods produces a vector of values that \ncan be used to index the loop:\n\n- `1:length(month.name)`\n- `1:12`\n- `seq_along(month.name)`\n- `seq_len(12)`\n- `month.name`\n\nSo, it is up to you to figure out what method makes the most sense to you! \n:::\n\n::: {.callout-check-in}\n10. Match the loop to its correct setting. \n\n::: columns\n::: {.column width=\"48%\"}\n\n`for()` Loop\n\n</br>\n\n`while()` Loop\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n\nRuns until a condition is not met (`FALSE`)\n\nRuns a set number of times\n:::\n:::\n\n11. Every `for()` loop has some derivation of `for (i in 1:10)`. The `i`\nrepresents the [counter / value / object], and the `1:10` represents the\n[list / dataframe / vector] of values to loop over.\n\n:::\n\n[^03-control-flow-4]: Yes, we know this is silly. We just printed all the names\nin the previous code chunk!\n\n",
    "supporting": [
      "03-control-flow_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}